### ISSUE TITLE
测试命令

### ISSUE THREAD

**Issue by LeiShenVictoria** [hengyicai/AdaND#1]
Use this to open other questions or issues, and provide context here.
您好，running部分只涉及到training的部分，请问测试命令和相关超参是什么呢？谢谢！

**Comment by hengyicai** [comment]
您好，这个脚本训练完成后会自动做测试。训练和测试时的超参是一样的，可以按照脚本中默认的或参照论文中的描述。

发自我的iPhone

在 2019年12月29日，下午3:52，LeiShenVictoria <notifications@github.com> 写道：

﻿

Use this to open other questions or issues, and provide context here.
您好，running部分只涉及到training的部分，请问测试命令和相关超参是什么呢？谢谢！
